version: "3"
  services:
    bot:
      build: .
      restart: "unless-stopped"
      depends_on:
        - db
    db:
      image: mongo:latest
      restart: "unless-stopped"
      ports:
        - "2717:27017"
      container_name: db
      volumes: ~/mongo/data:/data/db

